module.exports =  [
    "Yesterday's the past, tomorrow's the future, but today is a gift. That's why it's called the present.",
    "Time changes everything except something within us which is always surprised by change.",
    "Time moves in one direction, memory in another.",
    "Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent. Be careful lest you let other people spend it for you.",
    "Tough times never last, but tough people do.",
    "There are no secrets that time does not reveal.",
    "The time you enjoy wasting is not wasted time.",
    "Time is what we want most, but what we use worst.",
    "Lost time is never found again.",
    "Work is hard. Distractions are plentiful. And the future is radiant!",
    "Work is hard. Distractions are plentiful. And time is short.",
    "Men talk of killing time, while time quietly kills them.",
    "Until you value yourself, you won't value your time. Until you value your time, you will not do anything with it.",
    "Time brings all things to pass.",
    "Time you enjoy wasting, was not wasted.",
    "You may delay, but time will not.",
    "There's time enough, but none to spare.",
    "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time.",
    "Time is the wisest counselor of all.",
    "The future is radiant!",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Either you run the day, or the day runs you.",
    "You can’t have a better tomorrow if you are thinking about yesterday all the time.",
    "Better an hour too early than a minute too late.",
    "Your time is limited, so don’t waste it living someone else’s life.",
    "Either you run the day, or the day runs you",
    "There’s never enough time to do all the nothing you want.",
    "You can’t have a better tomorrow if you are thinking about yesterday all the time.",
    "Better an hour too early than a minute too late.",
    "Time cannot stop and does not wait."   
]

